# Generated by Django 2.2.7 on 2019-12-02 02:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IOTEWMPApp', '0011_delete_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturesensor',
            name='num',
            field=models.CharField(default=datetime.datetime(2019, 12, 2, 2, 27, 45, 716663, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
