# Generated by Django 2.2.7 on 2019-12-02 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IOTEWMPApp', '0012_temperaturesensor_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperaturesensor',
            name='num',
        ),
    ]
