# Generated by Django 2.2.7 on 2019-12-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTEWMPApp', '0013_remove_temperaturesensor_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturesensor',
            name='num',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
