# Generated by Django 2.2.7 on 2019-12-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTEWMPApp', '0015_auto_20191202_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodlightsensor',
            name='num',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humiditysensor',
            name='num',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
