# Generated by Django 2.2.7 on 2019-12-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTEWMPApp', '0016_auto_20191202_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodlightsensor',
            name='downdata',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floodlightsensor',
            name='updata',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humiditysensor',
            name='updata',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
